const aliases={date:['data','periodo','período','dia','mes','mês'],company:['empresa','unidade','operacao','operação'],product:['produto','empreendimento','imovel','imóvel'],agency:['imobiliaria','imobiliária','agencia','agência'],manager:['gerente','gestor'],broker:['corretor','consultor'],source:['origem','canal','fonte','tipo de venda'],leads:['leads','lead'],visits:['visitas','visita'],proposals:['propostas','proposta'],sales:['vendas','venda'],vgv:['vgv','valor','valor de venda','volume de vendas']};
let rows=[],filtered=[];
let areas=[];
const AREA_STORAGE='castel_brain_areas_v1';
const $=s=>document.querySelector(s), norm=v=>String(v??'').trim().toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v||0);
const number=v=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(v||0);
function detect(headers,key){const candidates=aliases[key].map(norm);return headers.find(h=>candidates.includes(norm(h)))||headers.find(h=>candidates.some(a=>norm(h).includes(a)));}
function numeric(v){if(typeof v==='number')return v;let s=String(v??'').replace(/R\$/gi,'').replace(/\s/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');return Number(s)||0;}
function shape(raw){const headers=Object.keys(raw[0]||{}),map=Object.fromEntries(Object.keys(aliases).map(k=>[k,detect(headers,k)]));return raw.map(r=>({date:r[map.date]||'',company:String(r[map.company]??'Não informado'),product:String(r[map.product]??'Não informado'),agency:String(r[map.agency]??'Não informado'),manager:String(r[map.manager]??'Não informado'),broker:String(r[map.broker]??'Não informado'),source:String(r[map.source]??'Não informado'),leads:numeric(r[map.leads]),visits:numeric(r[map.visits]),proposals:numeric(r[map.proposals]),sales:numeric(r[map.sales]),vgv:numeric(r[map.vgv])}));}
async function readFile(file){const buf=await file.arrayBuffer();if(file.name.toLowerCase().endsWith('.csv')){const text=new TextDecoder('utf-8').decode(buf),wb=XLSX.read(text,{type:'string'});return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});}const wb=XLSX.read(buf,{type:'array',cellDates:true});return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});}
function fillSelect(id,key){const el=$(id);el.innerHTML='<option value="">Todos</option>'+[...new Set(rows.map(r=>r[key]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(v=>`<option>${escapeHtml(v)}</option>`).join('');}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function group(key){const out={};for(const r of filtered){const name=r[key]||'Não informado';out[name]??={name,leads:0,visits:0,proposals:0,sales:0,vgv:0,manager:r.manager};for(const n of ['leads','visits','proposals','sales','vgv'])out[name][n]+=r[n];}return Object.values(out);}
function render(){const filters={product:$('#filter-product').value,agency:$('#filter-agency').value,manager:$('#filter-manager').value,broker:$('#filter-broker').value};filtered=rows.filter(r=>Object.entries(filters).every(([k,v])=>!v||r[k]===v));const sum=k=>filtered.reduce((a,r)=>a+r[k],0),leads=sum('leads'),visits=sum('visits'),proposals=sum('proposals'),sales=sum('sales'),vgv=sum('vgv'),conv=visits?sales/visits*100:0,ticket=sales?vgv/sales:0;$('#row-count').textContent=`${number(filtered.length)} registros analisados`;$('#metrics').innerHTML=[['Leads',number(leads)],['Visitas',number(visits)],['Propostas',number(proposals)],['Vendas',number(sales)],['VGV',money(vgv)],['Conversão visita → venda',`${conv.toFixed(2).replace('.',',')}%`],['Ticket médio',money(ticket)],['Conversão lead → venda',`${(leads?sales/leads*100:0).toFixed(2).replace('.',',')}%`]].map(([a,b])=>`<article class="metric"><span>${a}</span><strong>${b}</strong></article>`).join('');
 const products=group('product').sort((a,b)=>b.vgv-a.vgv).slice(0,12),agencies=group('agency').sort((a,b)=>b.sales-a.sales).slice(0,12),layout={margin:{l:48,r:12,t:18,b:90},paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{family:'Inter, sans-serif',color:'#526158'},xaxis:{tickangle:-30,gridcolor:'#edf0ed'},yaxis:{gridcolor:'#edf0ed'},showlegend:false};Plotly.react('product-chart',[{type:'bar',x:products.map(x=>x.name),y:products.map(x=>x.vgv),marker:{color:'#164a35'},hovertemplate:'%{x}<br>VGV: R$ %{y:,.0f}<extra></extra>'}],layout,{responsive:true,displayModeBar:false});Plotly.react('agency-chart',[{type:'bar',x:agencies.map(x=>x.name),y:agencies.map(x=>x.sales),marker:{color:'#c0dc61'},hovertemplate:'%{x}<br>Vendas: %{y}<extra></extra>'}],layout,{responsive:true,displayModeBar:false});
 const brokers=group('broker').sort((a,b)=>b.vgv-a.vgv).slice(0,20);$('#ranking-body').innerHTML=brokers.map((r,i)=>`<tr><td>${i+1}</td><td><strong>${escapeHtml(r.name)}</strong></td><td>${escapeHtml(r.manager)}</td><td>${number(r.visits)}</td><td>${number(r.sales)}</td><td>${(r.visits?r.sales/r.visits*100:0).toFixed(1).replace('.',',')}%</td><td><strong>${money(r.vgv)}</strong></td></tr>`).join('')||'<tr><td colspan="7">Nenhum registro para os filtros selecionados.</td></tr>';
}
$('#file-input').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;$('#file-status').textContent='Lendo o relatório no seu navegador…';try{const raw=await readFile(file);if(!raw.length)throw new Error('arquivo vazio');rows=shape(raw);['product','agency','manager','broker'].forEach(k=>fillSelect(`#filter-${k}`,k));$('#report-title').textContent=file.name.replace(/\.[^.]+$/,'');$('#upload-view').classList.add('hidden');$('#dashboard-view').classList.remove('hidden');render();}catch(err){$('#file-status').textContent='Não foi possível ler este arquivo. Verifique se a primeira linha contém os nomes das colunas.';}});
['product','agency','manager','broker'].forEach(k=>$(`#filter-${k}`).addEventListener('change',render));
$('#new-file').addEventListener('click',()=>{rows=[];filtered=[];$('#file-input').value='';$('#file-status').textContent='Formatos aceitos: Excel e CSV.';$('#dashboard-view').classList.add('hidden');$('#upload-view').classList.remove('hidden');});
$('#export-csv').addEventListener('click',()=>{const cols=['date','company','product','agency','manager','broker','source','leads','visits','proposals','sales','vgv'],labels=['Data','Empresa','Produto','Imobiliaria','Gerente','Corretor','Origem','Leads','Visitas','Propostas','Vendas','VGV'];const q=v=>`"${String(v??'').replace(/"/g,'""')}"`,csv='\ufeff'+labels.join(';')+'\n'+filtered.map(r=>cols.map(k=>q(r[k])).join(';')).join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='castel_brain_filtrado.csv';a.click();URL.revokeObjectURL(url);});

async function generatePresentation(){
 const button=$('#export-pptx');
 if(!filtered.length){alert('Carregue um relatório com dados antes de gerar a apresentação.');return;}
 if(typeof pptxgen==='undefined'){alert('O gerador de apresentações não carregou. Atualize a página e tente novamente.');return;}
 button.disabled=true;button.textContent='Gerando…';
 try{
  const pptx=new pptxgen();pptx.layout='LAYOUT_WIDE';pptx.author='Castel Brain';pptx.subject='Relatório executivo comercial';pptx.title='Castel Brain — Desempenho Comercial';pptx.company='Castel Brain';pptx.lang='pt-BR';pptx.theme={headFontFace:'Aptos Display',bodyFontFace:'Aptos',lang:'pt-BR'};
  const C={green:'164A35',lime:'CDE86B',ink:'17231D',muted:'66736C',paper:'F5F7F4',white:'FFFFFF',line:'DCE3DD'};
  const sum=k=>filtered.reduce((a,r)=>a+r[k],0),leads=sum('leads'),visits=sum('visits'),proposals=sum('proposals'),sales=sum('sales'),vgv=sum('vgv'),conv=visits?sales/visits:0,ticket=sales?vgv/sales:0;
  const fmt=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(n||0),brl=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n||0);
  const addBase=(slide,num)=>{slide.background={color:C.paper};slide.addText('CASTEL BRAIN',{x:.45,y:.23,w:2.2,h:.25,fontFace:'Aptos',fontSize:10,bold:true,color:C.green,charSpacing:1.5,margin:0});slide.addText(String(num).padStart(2,'0'),{x:12.15,y:7.08,w:.65,h:.2,fontSize:9,color:C.muted,align:'right',margin:0});};
  const addTitle=(slide,title,sub='',num=1)=>{addBase(slide,num);slide.addText(title,{x:.45,y:.65,w:12.1,h:.55,fontFace:'Aptos Display',fontSize:28,bold:true,color:C.ink,margin:0,breakLine:false});if(sub)slide.addText(sub,{x:.45,y:1.24,w:11.8,h:.35,fontSize:13,color:C.muted,margin:0});};
  const card=(slide,x,y,w,label,value,accent=C.green)=>{slide.addShape(pptx.ShapeType.roundRect,{x,y,w,h:1.12,rectRadius:.07,fill:{color:C.white},line:{color:C.line,width:1}});slide.addText(label.toUpperCase(),{x:x+.16,y:y+.15,w:w-.32,h:.18,fontSize:8,bold:true,color:C.muted,charSpacing:1,margin:0});slide.addText(value,{x:x+.16,y:y+.44,w:w-.32,h:.42,fontSize:22,bold:true,color:accent,margin:0,fit:'shrink'});};
  let slide=pptx.addSlide();slide.background={color:C.green};slide.addText('CASTEL BRAIN',{x:.55,y:.48,w:2.4,h:.3,fontSize:12,bold:true,color:C.lime,charSpacing:2,margin:0});slide.addText('Desempenho\nComercial',{x:.55,y:2.05,w:7.4,h:1.7,fontFace:'Aptos Display',fontSize:42,bold:true,color:C.white,margin:0,breakLine:false});slide.addText('Relatório executivo gerado a partir da base filtrada',{x:.58,y:4.05,w:6.8,h:.4,fontSize:17,color:'DDE8E1',margin:0});slide.addText(`${fmt(filtered.length)} registros analisados  •  ${new Date().toLocaleDateString('pt-BR')}`,{x:.58,y:6.52,w:5.8,h:.3,fontSize:12,color:C.lime,margin:0});slide.addShape(pptx.ShapeType.rect,{x:9.4,y:0,w:3.93,h:7.5,fill:{color:C.lime},line:{color:C.lime}});
  slide=pptx.addSlide();addTitle(slide,'Visão executiva','Os indicadores concentram o resultado da seleção atual.',2);[['Leads',fmt(leads)],['Visitas',fmt(visits)],['Propostas',fmt(proposals)],['Vendas',fmt(sales)],['VGV',brl(vgv)],['Conversão visita → venda',`${(conv*100).toFixed(1).replace('.',',')}%`],['Ticket médio',brl(ticket)],['Conversão lead → venda',`${(leads?sales/leads*100:0).toFixed(1).replace('.',',')}%`]].forEach((d,i)=>card(slide,.45+(i%4)*3.1,1.82+Math.floor(i/4)*1.45,2.85,d[0],d[1],i===4?C.green:C.ink));slide.addText(sales?'O resultado combina volume, conversão e valor gerado. Os próximos slides destacam onde a performance está concentrada.':'A base não registra vendas no recorte atual; priorize a revisão do funil e da qualidade dos registros.',{x:.55,y:5.3,w:11.7,h:.75,fontSize:20,bold:true,color:C.green,margin:0,breakLine:false});
  const productImg=await Plotly.toImage('product-chart',{format:'png',width:1200,height:600,scale:2});slide=pptx.addSlide();addTitle(slide,'Desempenho por produto','VGV acumulado por produto no recorte selecionado.',3);slide.addImage({data:productImg,x:.55,y:1.65,w:12.15,h:4.9});
  const agencyImg=await Plotly.toImage('agency-chart',{format:'png',width:1200,height:600,scale:2});slide=pptx.addSlide();addTitle(slide,'Desempenho por imobiliária','Vendas acumuladas por imobiliária no recorte selecionado.',4);slide.addImage({data:agencyImg,x:.55,y:1.65,w:12.15,h:4.9});
  const brokers=group('broker').sort((a,b)=>b.vgv-a.vgv).slice(0,10);slide=pptx.addSlide();addTitle(slide,'Ranking de corretores','Os dez maiores VGVs do recorte atual.',5);const rowsTable=[['#','Corretor','Gerente','Visitas','Vendas','Conversão','VGV'],...brokers.map((r,i)=>[String(i+1),r.name,r.manager,fmt(r.visits),fmt(r.sales),`${(r.visits?r.sales/r.visits*100:0).toFixed(1).replace('.',',')}%`,brl(r.vgv)])];slide.addTable(rowsTable,{x:.5,y:1.65,w:12.25,h:4.95,border:{type:'solid',color:C.line,pt:1},fill:C.white,color:C.ink,fontFace:'Aptos',fontSize:12,margin:.08,rowH:.36,autoFit:false,bold:false,headerRows:1});
  slide=pptx.addSlide();addTitle(slide,'Prioridades recomendadas','Três decisões para transformar leitura em ação.',6);const recs=[['1','Escalar o que já funciona',productsText()],['2','Atacar gargalos de conversão',`A conversão visita → venda está em ${(conv*100).toFixed(1).replace('.',',')}%. Analise perdas entre visita, proposta e fechamento.`],['3','Concentrar gestão comercial',brokers.length?`Reconheça os líderes do ranking e replique práticas de abordagem, acompanhamento e fechamento.`:'Complete o cadastro de corretores para identificar e comparar desempenho.']];recs.forEach((r,i)=>{const y=1.65+i*1.55;slide.addText(r[0],{x:.55,y,w:.62,h:.62,fontSize:24,bold:true,color:C.green,align:'center',valign:'mid',margin:0,fill:{color:C.lime},shape:pptx.ShapeType.ellipse});slide.addText(r[1],{x:1.45,y:y-.02,w:4.2,h:.35,fontSize:19,bold:true,color:C.ink,margin:0});slide.addText(r[2],{x:1.45,y:y+.42,w:10.6,h:.62,fontSize:14,color:C.muted,margin:0,breakLine:false});});
  function productsText(){const p=group('product').sort((a,b)=>b.vgv-a.vgv)[0];return p?`${p.name} lidera o VGV no recorte. Proteja o ritmo comercial e replique os canais que sustentam esse resultado.`:'Complete o campo Produto para identificar as principais fontes de VGV.';}
  await pptx.writeFile({fileName:`Castel_Brain_Relatorio_${new Date().toISOString().slice(0,10)}.pptx`});
 }catch(err){console.error(err);alert('Não foi possível gerar a apresentação. Atualize a página e tente novamente.');}
 finally{button.disabled=false;button.textContent='Gerar apresentação';}
}
$('#export-pptx').addEventListener('click',generatePresentation);

// Banco de áreas — dados salvos somente neste navegador.
function saveAreas(){localStorage.setItem(AREA_STORAGE,JSON.stringify(areas));renderAreas();}
function loadAreas(){try{areas=JSON.parse(localStorage.getItem(AREA_STORAGE)||'[]');if(!Array.isArray(areas))areas=[];}catch{areas=[];}renderAreas();}
function switchView(view){const reports=view==='reports';$('#areas-view').classList.toggle('hidden',reports);(rows.length?$('#dashboard-view'):$('#upload-view')).classList.toggle('hidden',!reports);if(reports){if(rows.length)$('#upload-view').classList.add('hidden');else $('#dashboard-view').classList.add('hidden');}document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='areas')renderAreas();}
document.querySelectorAll('.nav-link').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
function areaStatusClass(status){return norm(status).replace(/\s+/g,'-');}
function renderAreas(){const query=norm($('#area-search').value),status=$('#area-status-filter').value;const shown=areas.filter(a=>(!status||a.status===status)&&(!query||[a.code,a.name,a.city,a.neighborhood,a.owner].some(v=>norm(v).includes(query))));const totalSize=areas.reduce((s,a)=>s+numeric(a.size),0),totalValue=areas.reduce((s,a)=>s+numeric(a.value),0),negotiating=areas.filter(a=>a.status==='Negociação').length;$('#areas-summary').textContent=`${areas.length} ${areas.length===1?'área cadastrada':'áreas cadastradas'} neste navegador`;$('#area-stats').innerHTML=[['Áreas cadastradas',number(areas.length)],['Área total',`${number(totalSize)} m²`],['Valor solicitado',money(totalValue)],['Em negociação',number(negotiating)]].map(([a,b])=>`<article class="metric"><span>${a}</span><strong>${b}</strong></article>`).join('');$('#empty-areas').classList.toggle('hidden',areas.length>0);$('#areas-grid').classList.toggle('hidden',areas.length===0);$('#areas-grid').innerHTML=shown.map(a=>`<article class="area-card"><div class="area-card-head"><div><span class="area-code">${escapeHtml(a.code)}</span><h3>${escapeHtml(a.name)}</h3></div><span class="status-badge ${areaStatusClass(a.status)}">${escapeHtml(a.status)}</span></div><p class="area-location">${escapeHtml([a.neighborhood,a.city].filter(Boolean).join(' · '))}</p><div class="area-details"><div><span>Metragem</span><strong>${number(a.size)} m²</strong></div><div><span>Valor pedido</span><strong>${a.value?money(a.value):'Não informado'}</strong></div><div><span>Proprietário</span><strong>${escapeHtml(a.owner||'Não informado')}</strong></div><div><span>Contato</span><strong>${escapeHtml(a.phone||'Não informado')}</strong></div></div><div class="area-card-actions"><button class="small-button" data-edit="${a.id}">Editar</button><button class="small-button danger" data-delete="${a.id}">Excluir</button></div></article>`).join('')||(areas.length?'<article class="panel">Nenhuma área encontrada com esses filtros.</article>':'');document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openArea(b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>deleteArea(b.dataset.delete)));}
function openArea(id=''){const a=areas.find(x=>x.id===id);$('#area-form').reset();$('#area-id').value=a?.id||'';$('#area-dialog-title').textContent=a?'Editar área':'Nova área';for(const key of ['code','name','city','neighborhood','size','value','owner','phone','status','address','notes'])$(`#area-${key}`).value=a?.[key]??(key==='status'?'Prospecção':'');$('#area-dialog').showModal();}
function deleteArea(id){const a=areas.find(x=>x.id===id);if(a&&confirm(`Excluir a área ${a.code} — ${a.name}?`)){areas=areas.filter(x=>x.id!==id);saveAreas();}}
['#new-area','#first-area'].forEach(id=>$(id).addEventListener('click',()=>openArea()));
$('#area-search').addEventListener('input',renderAreas);$('#area-status-filter').addEventListener('change',renderAreas);
$('#area-form').addEventListener('submit',e=>{e.preventDefault();if(!e.submitter||e.submitter.value!=='default'){$('#area-dialog').close();return;}const id=$('#area-id').value||crypto.randomUUID(),record={id,updatedAt:new Date().toISOString()};for(const key of ['code','name','city','neighborhood','size','value','owner','phone','status','address','notes'])record[key]=$(`#area-${key}`).value.trim();record.size=numeric(record.size);record.value=numeric(record.value);const index=areas.findIndex(a=>a.id===id);if(index>=0)areas[index]={...areas[index],...record};else areas.unshift({...record,createdAt:new Date().toISOString()});saveAreas();$('#area-dialog').close();});
$('#backup-areas').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),areas},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`castel_brain_areas_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);});
$('#restore-areas').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text()),incoming=Array.isArray(data)?data:data.areas;if(!Array.isArray(incoming))throw new Error();if(areas.length&&!confirm('A importação substituirá o banco de áreas deste navegador. Continuar?'))return;areas=incoming;saveAreas();alert(`${areas.length} áreas importadas com sucesso.`);}catch{alert('Este arquivo não é um backup válido do Banco de Áreas.');}finally{e.target.value='';}});
loadAreas();

