const aliases={date:['data','periodo','período','dia','mes','mês'],company:['empresa','unidade','operacao','operação'],product:['produto','empreendimento','imovel','imóvel'],agency:['imobiliaria','imobiliária','agencia','agência'],manager:['gerente','gestor'],broker:['corretor','consultor'],source:['origem','canal','fonte','tipo de venda'],leads:['leads','lead'],visits:['visitas','visita'],proposals:['propostas','proposta'],sales:['vendas','venda'],vgv:['vgv','valor','valor de venda','volume de vendas']};
let rows=[],filtered=[];
const $=s=>document.querySelector(s), norm=v=>String(v??'').trim().toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v||0);
const number=v=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(v||0);
function detect(headers,key){const candidates=aliases[key].map(norm);return headers.find(h=>candidates.includes(norm(h)))||headers.find(h=>candidates.some(a=>norm(h).includes(a)));}
function numeric(v){if(typeof v==='number')return v;let s=String(v??'').replace(/R\$/gi,'').replace(/\s/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');return Number(s)||0;}
function shape(raw){const headers=Object.keys(raw[0]||{}),map=Object.fromEntries(Object.keys(aliases).map(k=>[k,detect(headers,k)]));return raw.map(r=>({date:r[map.date]||'',company:String(r[map.company]??'Não informado'),product:String(r[map.product]??'Não informado'),agency:String(r[map.agency]??'Não informado'),manager:String(r[map.manager]??'Não informado'),broker:String(r[map.broker]??'Não informado'),source:String(r[map.source]??'Não informado'),leads:numeric(r[map.leads]),visits:numeric(r[map.visits]),proposals:numeric(r[map.proposals]),sales:numeric(r[map.sales]),vgv:numeric(r[map.vgv])}));}
async function readFile(file){const buf=await file.arrayBuffer();if(file.name.toLowerCase().endsWith('.csv')){const text=new TextDecoder('utf-8').decode(buf),wb=XLSX.read(text,{type:'string'});return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});}const wb=XLSX.read(buf,{type:'array',cellDates:true});return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});}
function fillSelect(id,key){const el=$(id);el.innerHTML='<option value="">Todos</option>'+[...new Set(rows.map(r=>r[key]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(v=>`<option>${escapeHtml(v)}</option>`).join('');}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function group(key){const out={};for(const r of filtered){const name=r[key]||'Não informado';out[name]??={name,leads:0,visits:0,proposals:0,sales:0,vgv:0,manager:r.manager};for(const n of ['leads','visits','proposals','sales','vgv'])out[name][n]+=r[n];}return Object.values(out);}
function render(){const filters={product:$('#filter-product').value,agency:$('#filter-agency').value,manager:$('#filter-manager').value,broker:$('#filter-broker').value};filtered=rows.filter(r=>Object.entries(filters).every(([k,v])=>!v||r[k]===v));const sum=k=>filtered.reduce((a,r)=>a+r[k],0),leads=sum('leads'),visits=sum('visits'),proposals=sum('proposals'),sales=sum('sales'),vgv=sum('vgv'),conv=visits?sales/visits*100:0,ticket=sales?vgv/sales:0;$('#row-count').textContent=`${number(filtered.length)} registros analisados`;$('#metrics').innerHTML=[['Leads',number(leads)],['Visitas',number(visits)],['Propostas',number(proposals)],['Vendas',number(sales)],['VGV',money(vgv)],['Conversão visita → venda',`${conv.toFixed(2).replace('.',',')}%`],['Ticket médio',money(ticket)],['Conversão lead → venda',`${(leads?sales/leads*100:0).toFixed(2).replace('.',',')}%`]].map(([a,b])=>`<article class="metric"><span>${a}</span><strong>${b}</strong></article>`).join('');
 const products=group('product').sort((a,b)=>b.vgv-a.vgv).slice(0,12),agencies=group('agency').sort((a,b)=>b.sales-a.sales).slice(0,12),layout={margin:{l:48,r:12,t:18,b:90},paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{family:'Inter, sans-serif',color:'#526158'},xaxis:{tickangle:-30,gridcolor:'#edf0ed'},yaxis:{gridcolor:'#edf0ed'},showlegend:false};Plotly.react('product-chart',[{type:'bar',x:products.map(x=>x.name),y:products.map(x=>x.vgv),marker:{color:'#164a35'},hovertemplate:'%{x}<br>VGV: R$ %{y:,.0f}<extra></extra>'}],layout,{responsive:true,displayModeBar:false});Plotly.react('agency-chart',[{type:'bar',x:agencies.map(x=>x.name),y:agencies.map(x=>x.sales),marker:{color:'#c0dc61'},hovertemplate:'%{x}<br>Vendas: %{y}<extra></extra>'}],layout,{responsive:true,displayModeBar:false});
 const brokers=group('broker').sort((a,b)=>b.vgv-a.vgv).slice(0,20);$('#ranking-body').innerHTML=brokers.map((r,i)=>`<tr><td>${i+1}</td><td><strong>${escapeHtml(r.name)}</strong></td><td>${escapeHtml(r.manager)}</td><td>${number(r.visits)}</td><td>${number(r.sales)}</td><td>${(r.visits?r.sales/r.visits*100:0).toFixed(1).replace('.',',')}%</td><td><strong>${money(r.vgv)}</strong></td></tr>`).join('')||'<tr><td colspan="7">Nenhum registro para os filtros selecionados.</td></tr>';
}
$('#file-input').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;$('#file-status').textContent='Lendo o relatório no seu navegador…';try{const raw=await readFile(file);if(!raw.length)throw new Error('arquivo vazio');rows=shape(raw);['product','agency','manager','broker'].forEach(k=>fillSelect(`#filter-${k}`,k));$('#report-title').textContent=file.name.replace(/\.[^.]+$/,'');$('#upload-view').classList.add('hidden');$('#dashboard-view').classList.remove('hidden');render();}catch(err){$('#file-status').textContent='Não foi possível ler este arquivo. Verifique se a primeira linha contém os nomes das colunas.';}});
['product','agency','manager','broker'].forEach(k=>$(`#filter-${k}`).addEventListener('change',render));
$('#new-file').addEventListener('click',()=>{rows=[];filtered=[];$('#file-input').value='';$('#file-status').textContent='Formatos aceitos: Excel e CSV.';$('#dashboard-view').classList.add('hidden');$('#upload-view').classList.remove('hidden');});
$('#export-csv').addEventListener('click',()=>{const cols=['date','company','product','agency','manager','broker','source','leads','visits','proposals','sales','vgv'],labels=['Data','Empresa','Produto','Imobiliaria','Gerente','Corretor','Origem','Leads','Visitas','Propostas','Vendas','VGV'];const q=v=>`"${String(v??'').replace(/"/g,'""')}"`,csv='\ufeff'+labels.join(';')+'\n'+filtered.map(r=>cols.map(k=>q(r[k])).join(';')).join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='castel_brain_filtrado.csv';a.click();URL.revokeObjectURL(url);});

