const aliases={date:['data','periodo','período','dia','mes','mês'],company:['empresa','unidade','operacao','operação'],product:['produto','empreendimento','imovel','imóvel'],agency:['imobiliaria','imobiliária','agencia','agência'],manager:['gerente','gestor'],broker:['corretor','consultor'],source:['origem','canal','fonte','tipo de venda'],leads:['leads','lead'],visits:['visitas','visita'],proposals:['propostas','proposta'],sales:['vendas','venda'],vgv:['vgv','valor','valor de venda','volume de vendas']};
let rows=[],filtered=[],reportMode='commercial';
let importedRaw=[],currentMapping={};
let areas=[];
const AREA_STORAGE='castel_brain_areas_v1';
let reportHistory=[];
const REPORT_STORAGE='castel_brain_reports_v1';
let compareIds=[];
const $=s=>document.querySelector(s), norm=v=>String(v??'').trim().toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v||0);
const number=v=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(v||0);
function detect(headers,key){const candidates=aliases[key].map(norm);return headers.find(h=>candidates.includes(norm(h)))||headers.find(h=>candidates.some(a=>norm(h).includes(a)));}
function numeric(v){if(typeof v==='number')return v;let s=String(v??'').replace(/R\$/gi,'').replace(/\s/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');return Number(s)||0;}
function dateValue(v){if(!v)return null;if(v instanceof Date&&!isNaN(v))return v;if(typeof v==='number'&&window.XLSX?.SSF){const d=XLSX.SSF.parse_date_code(v);if(d)return new Date(d.y,d.m-1,d.d);}const s=String(v).trim(),br=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(br)return new Date(Number(br[3]),Number(br[2])-1,Number(br[1]));const d=new Date(s);return isNaN(d)?null:d;}
function isoDate(v){const d=dateValue(v);return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`:'';}
function configureDateFilters(){const dates=rows.map(r=>isoDate(r.date)).filter(Boolean).sort(),start=$('#filter-start'),end=$('#filter-end');start.value='';end.value='';start.disabled=!dates.length;end.disabled=!dates.length;if(dates.length){start.min=end.min=dates[0];start.max=end.max=dates.at(-1);}}
function shape(raw,overrides={}){const headers=Object.keys(raw[0]||{}),map=Object.fromEntries(Object.keys(aliases).map(k=>[k,Object.prototype.hasOwnProperty.call(overrides,k)?overrides[k]:detect(headers,k)]));return raw.map(r=>({date:r[map.date]||'',company:String(r[map.company]??r.company??'Não informado'),product:String(r[map.product]??'Não informado'),agency:String(r[map.agency]??r.agency??'Não informado'),manager:String(r[map.manager]??'Não informado'),broker:String(r[map.broker]??'Não informado'),source:String(r[map.source]??'Não informado'),leads:numeric(r[map.leads]),visits:numeric(r[map.visits]),proposals:numeric(r[map.proposals]),sales:numeric(r[map.sales]),vgv:numeric(r[map.vgv]),commissionBroker:numeric(r.commissionBroker),commissionManager:numeric(r.commissionManager),commissionDirector:numeric(r.commissionDirector),commissionCastel:numeric(r.commissionCastel),receivedRate:numeric(r.receivedRate),quadra:r.quadra??'',lote:r.lote??'',cliente:r.cliente??''}));}
function showImportDiagnostics(raw,mode,normalized=false,overrides=null){const labels={product:'Produto',agency:'Imobiliária',manager:'Gerente',broker:'Corretor',leads:'Leads',visits:'Visitas',proposals:'Propostas',sales:'Vendas',vgv:'VGV'},headers=Object.keys(raw[0]||{}),commissionFields=['product','manager','broker','sales','vgv'],found={};for(const key of Object.keys(labels))found[key]=overrides?Boolean(overrides[key]):mode==='commission'?commissionFields.includes(key):normalized?headers.includes(key):Boolean(detect(headers,key));const count=Object.values(found).filter(Boolean).length,total=Object.keys(found).length;$('#diagnostic-list').innerHTML=Object.entries(found).map(([key,ok])=>`<span class="diagnostic-item${ok?'':' missing'}">${ok?'✓':'!'} ${labels[key]}</span>`).join('');$('#import-quality').textContent=count===total?'Leitura completa':count>=5?'Leitura boa':'Revisar campos';$('#diagnostic-message').textContent=count===total?'Todos os campos principais foram identificados.':`Foram reconhecidos ${count} de ${total} campos. Itens em vermelho não existem ou usam um nome ainda não reconhecido nesta planilha.`;$('#open-mapping').classList.toggle('hidden',mode==='commission'||normalized);}
function parseCommissionWorkbook(wb){const primary=wb.SheetNames.filter(n=>!/^pagos\b/i.test(n)&&!/-1$/i.test(n)&&!/^resumo$/i.test(n)&&!/^gastos/i.test(n));const out=[];for(const sheetName of primary){const matrix=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{header:1,defval:'',raw:true});let header=null;for(const row of matrix){const normalized=row.map(norm);if(normalized.includes('loteamento')&&normalized.includes('pv')&&normalized.includes('corretor')){header=normalized;continue;}if(!header)continue;const at=(...names)=>{const idx=header.findIndex(h=>names.map(norm).includes(h));return idx>=0?row[idx]:'';};const product=at('loteamento'),pv=numeric(at('pv'));if(!product||norm(product)==='loteamento'||norm(product)==='total'||!pv)continue;let rate=numeric(at('recebido %','recebido'));if(rate>1)rate/=100;out.push({Produto:String(product),Gerente:sheetName,Corretor:String(at('corretor')||'Não informado'),Vendas:1,VGV:pv,company:'Castel',agency:sheetName,commissionBroker:numeric(at('valor corretor')),commissionManager:numeric(at('valor gerente')),commissionDirector:numeric(at('valor diretoria')),commissionCastel:numeric(at('valor castel')),receivedRate:rate,quadra:at('quadra'),lote:at('lote'),cliente:at('cliente','clente')});}}return out;}
async function readFile(file){const buf=await file.arrayBuffer();if(file.name.toLowerCase().endsWith('.csv')){const text=new TextDecoder('utf-8').decode(buf),wb=XLSX.read(text,{type:'string'});return {rows:XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''}),mode:'commercial'};}const wb=XLSX.read(buf,{type:'array',cellDates:true});const commissionRows=parseCommissionWorkbook(wb);if(commissionRows.length)return {rows:commissionRows,mode:'commission'};const generic=[];for(const name of wb.SheetNames){if(/^(resumo|gastos|pagos)|-1$/i.test(name))continue;const data=XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:''});if(!data.length)continue;const headers=Object.keys(data[0]),recognized=Object.keys(aliases).filter(k=>detect(headers,k)).length;if(recognized>=2)generic.push(...data);}return {rows:generic.length?generic:XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''}),mode:'commercial'};}
function fillSelect(id,key){const el=$(id);el.innerHTML='<option value="">Todos</option>'+[...new Set(rows.map(r=>r[key]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(v=>`<option>${escapeHtml(v)}</option>`).join('');if(key==='broker')configureDateFilters();}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function group(key){const out={};for(const r of filtered){const name=r[key]||'Não informado';out[name]??={name,leads:0,visits:0,proposals:0,sales:0,vgv:0,manager:r.manager};for(const n of ['leads','visits','proposals','sales','vgv'])out[name][n]+=r[n];}const result=Object.values(out);if(key==='manager')queueMicrotask(()=>{renderStrategicRankings();renderEvolution();});return result;}
function renderEvolution(){const byDate={};for(const r of filtered){const key=isoDate(r.date);if(!key)continue;byDate[key]??={sales:0,vgv:0};byDate[key].sales+=r.sales;byDate[key].vgv+=r.vgv;}const dates=Object.keys(byDate).sort(),panel=$('#evolution-panel');panel.classList.toggle('hidden',dates.length===0);if(!dates.length)return;Plotly.react('evolution-chart',[{name:'Vendas',type:'scatter',mode:'lines+markers',x:dates,y:dates.map(d=>byDate[d].sales),line:{color:'#164a35',width:3}},{name:'VGV',type:'bar',x:dates,y:dates.map(d=>byDate[d].vgv),marker:{color:'#cde86b'},yaxis:'y2'}],{margin:{l:55,r:70,t:25,b:70},paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{family:'Inter, sans-serif',color:'#526158'},legend:{orientation:'h'},xaxis:{gridcolor:'#edf0ed'},yaxis:{title:'Vendas',gridcolor:'#edf0ed'},yaxis2:{title:'VGV',overlaying:'y',side:'right',tickprefix:'R$ '}},{responsive:true,displayModeBar:false});}
function renderStrategicRankings(){const build=(key,target)=>{const ranked=group(key).filter(r=>r.name!=='Não informado').sort((a,b)=>b.sales-a.sales||b.vgv-a.vgv);$(target).innerHTML=ranked.map((r,i)=>`<tr><td>${i+1}</td><td><strong>${escapeHtml(r.name)}</strong></td><td>${number(r.leads)}</td><td>${number(r.sales)}</td><td>${(r.leads?r.sales/r.leads*100:0).toFixed(1).replace('.',',')}%</td><td><strong>${money(r.vgv)}</strong></td></tr>`).join('')||'<tr><td colspan="6">Campo não encontrado nesta planilha.</td></tr>';};build('product','#product-ranking-body');build('agency','#agency-ranking-body');}
function render(){const filters={product:$('#filter-product').value,agency:$('#filter-agency').value,manager:$('#filter-manager').value,broker:$('#filter-broker').value},start=$('#filter-start').value,end=$('#filter-end').value;filtered=rows.filter(r=>{const fields=Object.entries(filters).every(([k,v])=>!v||r[k]===v),date=isoDate(r.date);return fields&&(!start||date&&date>=start)&&(!end||date&&date<=end);});const sum=k=>filtered.reduce((a,r)=>a+(r[k]||0),0),leads=sum('leads'),visits=sum('visits'),proposals=sum('proposals'),sales=sum('sales'),vgv=sum('vgv'),conv=visits?sales/visits*100:0,ticket=sales?vgv/sales:0;$('#row-count').textContent=`${number(filtered.length)} registros analisados`;const metrics=reportMode==='commission'?[['Negócios',number(sales)],['VGV',money(vgv)],['Ticket médio',money(ticket)],['Comissão corretores',money(sum('commissionBroker'))],['Comissão gerência',money(sum('commissionManager'))],['Comissão diretoria',money(sum('commissionDirector'))],['Resultado Castel',money(sum('commissionCastel'))],['Comissões totais',money(sum('commissionBroker')+sum('commissionManager')+sum('commissionDirector')+sum('commissionCastel'))]]:[['Leads',number(leads)],['Visitas',number(visits)],['Propostas',number(proposals)],['Vendas',number(sales)],['VGV',money(vgv)],['Conversão visita → venda',`${conv.toFixed(2).replace('.',',')}%`],['Ticket médio',money(ticket)],['Conversão lead → venda',`${(leads?sales/leads*100:0).toFixed(2).replace('.',',')}%`]];$('#metrics').innerHTML=metrics.map(([a,b])=>`<article class="metric"><span>${a}</span><strong>${b}</strong></article>`).join('');
 const products=group('product').sort((a,b)=>b.vgv-a.vgv).slice(0,12),agencies=group(reportMode==='commission'?'manager':'agency').sort((a,b)=>reportMode==='commission'?b.vgv-a.vgv:b.sales-a.sales).slice(0,12),layout={margin:{l:48,r:12,t:18,b:90},paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{family:'Inter, sans-serif',color:'#526158'},xaxis:{tickangle:-30,gridcolor:'#edf0ed'},yaxis:{gridcolor:'#edf0ed'},showlegend:false};$('#product-chart-title').textContent='VGV por loteamento';$('#agency-chart-title').textContent=reportMode==='commission'?'VGV por responsável':'Vendas por imobiliária';Plotly.react('product-chart',[{type:'bar',x:products.map(x=>x.name),y:products.map(x=>x.vgv),marker:{color:'#164a35'},hovertemplate:'%{x}<br>VGV: R$ %{y:,.0f}<extra></extra>'}],layout,{responsive:true,displayModeBar:false});Plotly.react('agency-chart',[{type:'bar',x:agencies.map(x=>x.name),y:agencies.map(x=>reportMode==='commission'?x.vgv:x.sales),marker:{color:'#c0dc61'},hovertemplate:reportMode==='commission'?'%{x}<br>VGV: R$ %{y:,.0f}<extra></extra>':'%{x}<br>Vendas: %{y}<extra></extra>'}],layout,{responsive:true,displayModeBar:false});const financialPanel=$('#financial-panel');financialPanel.classList.toggle('hidden',reportMode!=='commission');if(reportMode==='commission'){const finance={};for(const r of filtered){const key=r.manager||'Não informado',total=r.commissionBroker+r.commissionManager+r.commissionDirector+r.commissionCastel;finance[key]??={received:0,pending:0};finance[key].received+=total*r.receivedRate;finance[key].pending+=Math.max(total*(1-r.receivedRate),0);}const names=Object.keys(finance);Plotly.react('financial-chart',[{name:'Recebido',type:'bar',x:names,y:names.map(n=>finance[n].received),marker:{color:'#164a35'}},{name:'Pendente',type:'bar',x:names,y:names.map(n=>finance[n].pending),marker:{color:'#d7a949'}}],{...layout,barmode:'stack',showlegend:true,legend:{orientation:'h',y:1.12},yaxis:{...layout.yaxis,tickprefix:'R$ '}},{responsive:true,displayModeBar:false});}
 const managers=group('manager').sort((a,b)=>b.vgv-a.vgv),managerTotal=managers.reduce((s,r)=>s+r.vgv,0);$('#manager-ranking-body').innerHTML=managers.map((r,i)=>`<tr><td>${i+1}</td><td><strong>${escapeHtml(r.name)}</strong></td><td>${number(r.sales)}</td><td><strong>${money(r.vgv)}</strong></td><td>${money(r.sales?r.vgv/r.sales:0)}</td><td>${(managerTotal?r.vgv/managerTotal*100:0).toFixed(1).replace('.',',')}%</td></tr>`).join('')||'<tr><td colspan="6">Nenhum gerente encontrado.</td></tr>';const brokers=group('broker').sort((a,b)=>b.vgv-a.vgv).slice(0,20);$('#ranking-body').innerHTML=brokers.map((r,i)=>`<tr><td>${i+1}</td><td><strong>${escapeHtml(r.name)}</strong></td><td>${escapeHtml(r.manager)}</td><td>${number(r.visits)}</td><td>${number(r.sales)}</td><td>${(r.visits?r.sales/r.visits*100:0).toFixed(1).replace('.',',')}%</td><td><strong>${money(r.vgv)}</strong></td></tr>`).join('')||'<tr><td colspan="7">Nenhum registro para os filtros selecionados.</td></tr>';const detailPanel=$('#sales-detail-panel');detailPanel.classList.toggle('hidden',reportMode!=='commission');if(reportMode==='commission'){const ordered=[...filtered].sort((a,b)=>b.vgv-a.vgv);$('#sales-detail-count').textContent=`${number(ordered.length)} negócios`;$('#sales-detail-body').innerHTML=ordered.map(r=>{const commission=r.commissionBroker+r.commissionManager+r.commissionDirector+r.commissionCastel,received=commission*r.receivedRate,pending=Math.max(commission-received,0);return `<tr><td><strong>${escapeHtml(r.manager)}</strong></td><td>${escapeHtml(r.product)}</td><td>${escapeHtml(r.quadra||'—')}</td><td>${escapeHtml(r.lote||'—')}</td><td>${escapeHtml(r.cliente||'—')}</td><td>${escapeHtml(r.broker)}</td><td><strong>${money(r.vgv)}</strong></td><td>${money(received)}</td><td>${money(pending)}</td></tr>`;}).join('')||'<tr><td colspan="9">Nenhum negócio para os filtros selecionados.</td></tr>';}
}
$('#file-input').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;$('#file-status').textContent='Lendo todas as abas do relatório no seu navegador…';try{const result=await readFile(file);if(!result.rows.length)throw new Error('arquivo vazio');reportMode=result.mode;importedRaw=result.rows;currentMapping={};showImportDiagnostics(result.rows,result.mode);rows=shape(result.rows);['product','agency','manager','broker'].forEach(k=>fillSelect(`#filter-${k}`,k));$('#report-title').textContent=file.name.replace(/\.[^.]+$/,'');$('#upload-view').classList.add('hidden');$('#dashboard-view').classList.remove('hidden');render();}catch(err){console.error(err);$('#file-status').textContent='Não foi possível reconhecer os dados deste arquivo.';}});
$('#open-mapping').addEventListener('click',()=>{if(!importedRaw.length)return;const labels={product:'Produto',agency:'Imobiliária',manager:'Gerente',broker:'Corretor',leads:'Leads',visits:'Visitas',proposals:'Propostas',sales:'Vendas',vgv:'VGV'},headers=Object.keys(importedRaw[0]||{});$('#mapping-grid').innerHTML=Object.entries(labels).map(([key,label])=>{const selected=Object.prototype.hasOwnProperty.call(currentMapping,key)?currentMapping[key]:detect(headers,key)||'';return `<div><label for="mapping-${key}">${label}</label><select id="mapping-${key}" data-map-key="${key}"><option value="">Não informado</option>${headers.map(h=>`<option value="${escapeHtml(h)}"${h===selected?' selected':''}>${escapeHtml(h)}</option>`).join('')}</select></div>`;}).join('');$('#mapping-dialog').showModal();});
$('#mapping-form').addEventListener('submit',e=>{e.preventDefault();if(!e.submitter||e.submitter.value!=='default'){$('#mapping-dialog').close();return;}currentMapping={};document.querySelectorAll('[data-map-key]').forEach(select=>currentMapping[select.dataset.mapKey]=select.value);rows=shape(importedRaw,currentMapping);showImportDiagnostics(importedRaw,reportMode,false,currentMapping);['product','agency','manager','broker'].forEach(k=>fillSelect(`#filter-${k}`,k));render();$('#mapping-dialog').close();});
['product','agency','manager','broker'].forEach(k=>$(`#filter-${k}`).addEventListener('change',render));
['#filter-start','#filter-end'].forEach(id=>$(id).addEventListener('change',render));
$('#new-file').addEventListener('click',()=>{rows=[];filtered=[];$('#file-input').value='';$('#file-status').textContent='Formatos aceitos: Excel e CSV.';$('#dashboard-view').classList.add('hidden');$('#upload-view').classList.remove('hidden');});
$('#save-history').addEventListener('click',()=>{if(!rows.length)return;const snapshot={id:crypto.randomUUID(),name:$('#report-title').textContent||'Relatório',savedAt:new Date().toISOString(),mode:reportMode,rows};try{reportHistory.unshift(snapshot);localStorage.setItem(REPORT_STORAGE,JSON.stringify(reportHistory));renderHistory();alert('Relatório salvo no histórico deste navegador.');}catch(err){reportHistory.shift();alert('Não há espaço suficiente no navegador. Exclua um relatório antigo e tente novamente.');}});
$('#export-csv').addEventListener('click',()=>{const commission=reportMode==='commission',cols=commission?['manager','product','quadra','lote','cliente','broker','sales','vgv','commissionBroker','commissionManager','commissionDirector','commissionCastel','receivedRate']:['date','company','product','agency','manager','broker','source','leads','visits','proposals','sales','vgv'],labels=commission?['Responsável','Loteamento','Quadra','Lote','Cliente','Corretor','Negócios','PV / VGV','Valor Corretor','Valor Gerente','Valor Diretoria','Valor Castel','Recebido %']:['Data','Empresa','Produto','Imobiliária','Gerente','Corretor','Origem','Leads','Visitas','Propostas','Vendas','VGV'];const q=v=>`"${String(v??'').replace(/"/g,'""')}"`,csv='\ufeff'+labels.join(';')+'\n'+filtered.map(r=>cols.map(k=>q(r[k])).join(';')).join('\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=commission?'castel_brain_negocios.csv':'castel_brain_filtrado.csv';a.click();URL.revokeObjectURL(url);});

async function generatePresentation(){
 const button=$('#export-pptx');
 if(!filtered.length){alert('Carregue um relatório com dados antes de gerar a apresentação.');return;}
 const PptxCtor=window.pptxgen||window.PptxGenJS;
 if(!PptxCtor){alert('O gerador de apresentações não carregou. Atualize a página e tente novamente.');return;}
 button.disabled=true;button.textContent='Gerando…';
 try{
  const pptx=new PptxCtor();pptx.layout='LAYOUT_WIDE';pptx.author='Castel Brain';pptx.subject='Relatório executivo comercial';pptx.title='Castel Brain — Desempenho Comercial';pptx.company='Castel Brain';pptx.lang='pt-BR';pptx.theme={headFontFace:'Aptos Display',bodyFontFace:'Aptos',lang:'pt-BR'};
  const C={green:'164A35',lime:'CDE86B',ink:'17231D',muted:'66736C',paper:'F5F7F4',white:'FFFFFF',line:'DCE3DD'};
  const sum=k=>filtered.reduce((a,r)=>a+(Number(r[k])||0),0),leads=sum('leads'),visits=sum('visits'),proposals=sum('proposals'),sales=sum('sales'),vgv=sum('vgv'),conv=visits?sales/visits:0,ticket=sales?vgv/sales:0,brokerCommission=sum('commissionBroker'),managerCommission=sum('commissionManager'),directorCommission=sum('commissionDirector'),castelCommission=sum('commissionCastel');
  const fmt=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(n||0),brl=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n||0);
  const addBase=(slide,num)=>{slide.background={color:C.paper};slide.addText('CASTEL BRAIN',{x:.45,y:.23,w:2.2,h:.25,fontFace:'Aptos',fontSize:10,bold:true,color:C.green,charSpacing:1.5,margin:0});slide.addText(String(num).padStart(2,'0'),{x:12.15,y:7.08,w:.65,h:.2,fontSize:9,color:C.muted,align:'right',margin:0});};
  const addTitle=(slide,title,sub='',num=1)=>{addBase(slide,num);slide.addText(title,{x:.45,y:.62,w:12.1,h:.62,fontFace:'Aptos Display',fontSize:35,bold:true,color:C.ink,margin:0,breakLine:false});if(sub)slide.addText(sub,{x:.45,y:1.28,w:11.8,h:.35,fontSize:16,color:C.muted,margin:0});};
  const card=(slide,x,y,w,label,value,accent=C.green)=>{slide.addShape(pptx.ShapeType.roundRect,{x,y,w,h:1.12,rectRadius:.07,fill:{color:C.white},line:{color:C.line,width:1}});slide.addText(label.toUpperCase(),{x:x+.16,y:y+.15,w:w-.32,h:.18,fontSize:8,bold:true,color:C.muted,charSpacing:1,margin:0});slide.addText(value,{x:x+.16,y:y+.44,w:w-.32,h:.42,fontSize:22,bold:true,color:accent,margin:0,fit:'shrink'});};
  let slide=pptx.addSlide();slide.background={color:C.green};slide.addText('CASTEL BRAIN',{x:.55,y:.48,w:2.4,h:.3,fontSize:12,bold:true,color:C.lime,charSpacing:2,margin:0});slide.addText('Desempenho\nComercial',{x:.55,y:2.05,w:7.4,h:1.7,fontFace:'Aptos Display',fontSize:42,bold:true,color:C.white,margin:0,breakLine:false});slide.addText('Relatório executivo gerado a partir da base filtrada',{x:.58,y:4.05,w:6.8,h:.4,fontSize:17,color:'DDE8E1',margin:0});slide.addText(`${fmt(filtered.length)} registros analisados  •  ${new Date().toLocaleDateString('pt-BR')}`,{x:.58,y:6.52,w:5.8,h:.3,fontSize:12,color:C.lime,margin:0});slide.addShape(pptx.ShapeType.rect,{x:9.4,y:0,w:3.93,h:7.5,fill:{color:C.lime},line:{color:C.lime}});
  slide=pptx.addSlide();addTitle(slide,'Visão executiva','Os indicadores concentram o resultado da seleção atual.',2);const executiveCards=reportMode==='commission'?[['Negócios',fmt(sales)],['VGV',brl(vgv)],['Ticket médio',brl(ticket)],['Corretores',brl(brokerCommission)],['Gerência',brl(managerCommission)],['Diretoria',brl(directorCommission)],['Resultado Castel',brl(castelCommission)],['Comissões totais',brl(brokerCommission+managerCommission+directorCommission+castelCommission)]]:[['Leads',fmt(leads)],['Visitas',fmt(visits)],['Propostas',fmt(proposals)],['Vendas',fmt(sales)],['VGV',brl(vgv)],['Conversão visita → venda',`${(conv*100).toFixed(1).replace('.',',')}%`],['Ticket médio',brl(ticket)],['Conversão lead → venda',`${(leads?sales/leads*100:0).toFixed(1).replace('.',',')}%`]];executiveCards.forEach((d,i)=>card(slide,.45+(i%4)*3.1,1.82+Math.floor(i/4)*1.45,2.85,d[0],d[1],i===1?C.green:C.ink));slide.addText(reportMode==='commission'?'A leitura consolida somente as abas principais e desconsidera abas Pagos, cópias “-1”, Resumo e Gastos.':'O resultado combina volume, conversão e valor gerado. Os próximos slides destacam onde a performance está concentrada.',{x:.55,y:5.3,w:11.7,h:.75,fontSize:20,bold:true,color:C.green,margin:0,breakLine:false});
  const productImg=await Plotly.toImage(document.getElementById('product-chart'),{format:'png',width:1200,height:600,scale:2});slide=pptx.addSlide();addTitle(slide,'Desempenho por loteamento','VGV acumulado por loteamento no recorte selecionado.',3);slide.addImage({data:productImg,x:.55,y:1.65,w:12.15,h:4.9});
  const agencyImg=await Plotly.toImage(document.getElementById('agency-chart'),{format:'png',width:1200,height:600,scale:2});slide=pptx.addSlide();addTitle(slide,reportMode==='commission'?'VGV por responsável':'Desempenho por imobiliária',reportMode==='commission'?'Comparação entre as abas principais da planilha.':'Vendas acumuladas por imobiliária no recorte selecionado.',4);slide.addImage({data:agencyImg,x:.55,y:1.65,w:12.15,h:4.9});
  if(reportMode==='commission'){const financialImg=await Plotly.toImage(document.getElementById('financial-chart'),{format:'png',width:1200,height:600,scale:2});slide=pptx.addSlide();addTitle(slide,'O saldo a receber exige acompanhamento','Comissões recebidas e pendentes por responsável.',5);slide.addImage({data:financialImg,x:.55,y:1.65,w:12.15,h:4.9});}
  const brokers=group('broker').sort((a,b)=>b.vgv-a.vgv).slice(0,10);slide=pptx.addSlide();addTitle(slide,'O VGV está concentrado nos líderes','Os dez maiores VGVs do recorte atual.',reportMode==='commission'?6:5);const rowsTable=reportMode==='commission'?[['#','Corretor','Responsável','Negócios','Ticket médio','Participação','VGV'],...brokers.map((r,i)=>[String(i+1),r.name,r.manager,fmt(r.sales),brl(r.sales?r.vgv/r.sales:0),`${(vgv?r.vgv/vgv*100:0).toFixed(1).replace('.',',')}%`,brl(r.vgv)])]:[['#','Corretor','Gerente','Visitas','Vendas','Conversão','VGV'],...brokers.map((r,i)=>[String(i+1),r.name,r.manager,fmt(r.visits),fmt(r.sales),`${(r.visits?r.sales/r.visits*100:0).toFixed(1).replace('.',',')}%`,brl(r.vgv)])];slide.addTable(rowsTable,{x:.5,y:1.65,w:12.25,h:4.95,border:{type:'solid',color:C.line,pt:1},fill:C.white,color:C.ink,fontFace:'Aptos',fontSize:16,margin:.08,rowH:.36,autoFit:false,bold:false,headerRows:1});
  slide=pptx.addSlide();addTitle(slide,'Prioridades recomendadas','Três decisões para transformar leitura em ação.',reportMode==='commission'?7:6);const recs=reportMode==='commission'?[['1','Proteger os loteamentos líderes',productsText()],['2','Cobrar o saldo pendente','Priorize os negócios com menor percentual recebido e maior comissão ainda em aberto.'],['3','Replicar o desempenho dos líderes',brokers.length?'Use o ranking de VGV para reconhecer os destaques e compartilhar práticas comerciais.':'Complete o cadastro de corretores para comparar o desempenho.']]:[['1','Escalar o que já funciona',productsText()],['2','Atacar gargalos de conversão',`A conversão visita → venda está em ${(conv*100).toFixed(1).replace('.',',')}%. Analise perdas entre visita, proposta e fechamento.`],['3','Concentrar gestão comercial',brokers.length?'Reconheça os líderes do ranking e replique práticas de abordagem, acompanhamento e fechamento.':'Complete o cadastro de corretores para identificar e comparar desempenho.']];recs.forEach((r,i)=>{const y=1.65+i*1.55;slide.addText(r[0],{x:.55,y,w:.62,h:.62,fontSize:24,bold:true,color:C.green,align:'center',valign:'mid',margin:0,fill:{color:C.lime},shape:pptx.ShapeType.ellipse});slide.addText(r[1],{x:1.45,y:y-.02,w:4.2,h:.35,fontSize:24,bold:true,color:C.ink,margin:0});slide.addText(r[2],{x:1.45,y:y+.42,w:10.6,h:.62,fontSize:16,color:C.muted,margin:0,breakLine:false});});
  function productsText(){const p=group('product').sort((a,b)=>b.vgv-a.vgv)[0];return p?`${p.name} lidera o VGV no recorte. Proteja o ritmo comercial e replique os canais que sustentam esse resultado.`:'Complete o campo Produto para identificar as principais fontes de VGV.';}
  await pptx.writeFile({fileName:`Castel_Brain_Relatorio_${new Date().toISOString().slice(0,10)}.pptx`});
 }catch(err){console.error(err);alert('Não foi possível gerar a apresentação. Atualize a página e tente novamente.');}
 finally{button.disabled=false;button.textContent='Gerar apresentação';}
}
$('#export-pptx').addEventListener('click',generatePresentation);

// Banco de áreas — dados salvos somente neste navegador.
function saveAreas(){localStorage.setItem(AREA_STORAGE,JSON.stringify(areas));renderAreas();}
function loadAreas(){try{areas=JSON.parse(localStorage.getItem(AREA_STORAGE)||'[]');if(!Array.isArray(areas))areas=[];}catch{areas=[];}renderAreas();}
function loadHistory(){try{reportHistory=JSON.parse(localStorage.getItem(REPORT_STORAGE)||'[]');if(!Array.isArray(reportHistory))reportHistory=[];}catch{reportHistory=[];}renderHistory();}
function reportSummary(h){const sum=k=>h.rows.reduce((s,r)=>s+(Number(r[k])||0),0),leads=sum('leads'),sales=sum('sales'),vgv=sum('vgv');return {leads,sales,vgv,conversion:leads?sales/leads*100:0,ticket:sales?vgv/sales:0};}
function renderHistory(){const grid=$('#history-grid'),empty=$('#empty-history');$('#history-summary').textContent=`${reportHistory.length} ${reportHistory.length===1?'relatório salvo':'relatórios salvos'} neste navegador · selecione dois para comparar`;empty.classList.toggle('hidden',reportHistory.length>0);grid.classList.toggle('hidden',reportHistory.length===0);grid.innerHTML=reportHistory.map(h=>{const s=reportSummary(h),selected=compareIds.includes(h.id);return `<article class="area-card${selected?' selected':''}"><div class="area-card-head"><div><span class="area-code">${new Date(h.savedAt).toLocaleString('pt-BR')}</span><h3>${escapeHtml(h.name)}</h3></div><span class="status-badge">${h.mode==='commission'?'Comissões':'Comercial'}</span></div><div class="area-details"><div><span>Registros</span><strong>${number(h.rows.length)}</strong></div><div><span>VGV</span><strong>${money(s.vgv)}</strong></div><div><span>Vendas</span><strong>${number(s.sales)}</strong></div><div><span>Leads</span><strong>${number(s.leads)}</strong></div></div><div class="area-card-actions"><button class="small-button" data-compare-report="${h.id}">${selected?'Selecionado':'Comparar'}</button><button class="small-button" data-open-report="${h.id}">Abrir</button><button class="small-button danger" data-delete-report="${h.id}">Excluir</button></div></article>`;}).join('');document.querySelectorAll('[data-compare-report]').forEach(b=>b.addEventListener('click',()=>toggleComparison(b.dataset.compareReport)));document.querySelectorAll('[data-open-report]').forEach(b=>b.addEventListener('click',()=>openHistoryReport(b.dataset.openReport)));document.querySelectorAll('[data-delete-report]').forEach(b=>b.addEventListener('click',()=>deleteHistoryReport(b.dataset.deleteReport)));renderComparison();}
function toggleComparison(id){if(compareIds.includes(id))compareIds=compareIds.filter(x=>x!==id);else{if(compareIds.length===2)compareIds.shift();compareIds.push(id);}renderHistory();}
function renderComparison(){const selected=compareIds.map(id=>reportHistory.find(h=>h.id===id)).filter(Boolean),panel=$('#comparison-panel');panel.classList.toggle('hidden',selected.length!==2);if(selected.length!==2)return;const [a,b]=selected,sa=reportSummary(a),sb=reportSummary(b),change=(oldValue,newValue)=>oldValue?(newValue-oldValue)/oldValue*100:0,items=[['Leads',sa.leads,sb.leads,false],['Vendas',sa.sales,sb.sales,false],['Conversão',sa.conversion,sb.conversion,true],['VGV',sa.vgv,sb.vgv,false],['Ticket médio',sa.ticket,sb.ticket,false]];$('#comparison-title').textContent=`${a.name} × ${b.name}`;$('#comparison-metrics').innerHTML=items.map(([label,oldValue,newValue,percent])=>{const delta=change(oldValue,newValue),format=percent?`${newValue.toFixed(1).replace('.',',')}%`:label.includes('VGV')||label.includes('Ticket')?money(newValue):number(newValue);return `<article class="metric"><span>${label} · período mais recente</span><strong>${format}</strong><small class="${delta>=0?'positive':'negative'}">${delta>=0?'▲':'▼'} ${Math.abs(delta).toFixed(1).replace('.',',')}%</small></article>`;}).join('');Plotly.react('comparison-chart',items.map(([label,oldValue,newValue])=>({type:'bar',name:label,x:[a.name,b.name],y:[oldValue,newValue]})),{barmode:'group',margin:{l:55,r:15,t:35,b:80},paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{family:'Inter, sans-serif',color:'#526158'},legend:{orientation:'h'},xaxis:{tickangle:-15},yaxis:{gridcolor:'#edf0ed'}},{responsive:true,displayModeBar:false});}
$('#clear-comparison').addEventListener('click',()=>{compareIds=[];renderHistory();});
function openHistoryReport(id){const h=reportHistory.find(x=>x.id===id);if(!h)return;rows=h.rows;reportMode=h.mode;showImportDiagnostics(h.rows,h.mode,true);['product','agency','manager','broker'].forEach(k=>fillSelect(`#filter-${k}`,k));$('#report-title').textContent=h.name;render();switchView('reports');}
function deleteHistoryReport(id){const h=reportHistory.find(x=>x.id===id);if(h&&confirm(`Excluir ${h.name} do histórico local?`)){reportHistory=reportHistory.filter(x=>x.id!==id);localStorage.setItem(REPORT_STORAGE,JSON.stringify(reportHistory));renderHistory();}}
function switchView(view){const reports=view==='reports',areas=view==='areas',history=view==='history';$('#areas-view').classList.toggle('hidden',!areas);$('#history-view').classList.toggle('hidden',!history);$('#upload-view').classList.toggle('hidden',!reports||rows.length>0);$('#dashboard-view').classList.toggle('hidden',!reports||rows.length===0);document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(areas)renderAreas();if(history)renderHistory();}
document.querySelectorAll('.nav-link').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
function areaStatusClass(status){return norm(status).replace(/\s+/g,'-');}
function renderAreas(){const query=norm($('#area-search').value),status=$('#area-status-filter').value;const shown=areas.filter(a=>(!status||a.status===status)&&(!query||[a.code,a.name,a.city,a.neighborhood,a.owner].some(v=>norm(v).includes(query))));const totalSize=areas.reduce((s,a)=>s+numeric(a.size),0),totalValue=areas.reduce((s,a)=>s+numeric(a.value),0),negotiating=areas.filter(a=>a.status==='Negociação').length;$('#areas-summary').textContent=`${areas.length} ${areas.length===1?'área cadastrada':'áreas cadastradas'} neste navegador`;$('#area-stats').innerHTML=[['Áreas cadastradas',number(areas.length)],['Área total',`${number(totalSize)} m²`],['Valor solicitado',money(totalValue)],['Em negociação',number(negotiating)]].map(([a,b])=>`<article class="metric"><span>${a}</span><strong>${b}</strong></article>`).join('');$('#empty-areas').classList.toggle('hidden',areas.length>0);$('#areas-grid').classList.toggle('hidden',areas.length===0);$('#areas-grid').innerHTML=shown.map(a=>`<article class="area-card"><div class="area-card-head"><div><span class="area-code">${escapeHtml(a.code)}</span><h3>${escapeHtml(a.name)}</h3></div><span class="status-badge ${areaStatusClass(a.status)}">${escapeHtml(a.status)}</span></div><p class="area-location">${escapeHtml([a.neighborhood,a.city].filter(Boolean).join(' · '))}</p><div class="area-details"><div><span>Metragem</span><strong>${number(a.size)} m²</strong></div><div><span>Valor pedido</span><strong>${a.value?money(a.value):'Não informado'}</strong></div><div><span>Proprietário</span><strong>${escapeHtml(a.owner||'Não informado')}</strong></div><div><span>Contato</span><strong>${escapeHtml(a.phone||'Não informado')}</strong></div></div><div class="area-card-actions"><button class="small-button" data-edit="${a.id}">Editar</button><button class="small-button danger" data-delete="${a.id}">Excluir</button></div></article>`).join('')||(areas.length?'<article class="panel">Nenhuma área encontrada com esses filtros.</article>':'');document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openArea(b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>deleteArea(b.dataset.delete)));}
function openArea(id=''){const a=areas.find(x=>x.id===id);$('#area-form').reset();$('#area-id').value=a?.id||'';$('#area-dialog-title').textContent=a?'Editar área':'Nova área';for(const key of ['code','name','city','neighborhood','size','value','owner','phone','status','address','notes'])$(`#area-${key}`).value=a?.[key]??(key==='status'?'Prospecção':'');$('#area-dialog').showModal();}
function deleteArea(id){const a=areas.find(x=>x.id===id);if(a&&confirm(`Excluir a área ${a.code} — ${a.name}?`)){areas=areas.filter(x=>x.id!==id);saveAreas();}}
['#new-area','#first-area'].forEach(id=>$(id).addEventListener('click',()=>openArea()));
$('#area-search').addEventListener('input',renderAreas);$('#area-status-filter').addEventListener('change',renderAreas);
$('#area-form').addEventListener('submit',e=>{e.preventDefault();if(!e.submitter||e.submitter.value!=='default'){$('#area-dialog').close();return;}const id=$('#area-id').value||crypto.randomUUID(),record={id,updatedAt:new Date().toISOString()};for(const key of ['code','name','city','neighborhood','size','value','owner','phone','status','address','notes'])record[key]=$(`#area-${key}`).value.trim();record.size=numeric(record.size);record.value=numeric(record.value);const index=areas.findIndex(a=>a.id===id);if(index>=0)areas[index]={...areas[index],...record};else areas.unshift({...record,createdAt:new Date().toISOString()});saveAreas();$('#area-dialog').close();});
$('#backup-areas').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),areas},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`castel_brain_areas_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);});
$('#restore-areas').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text()),incoming=Array.isArray(data)?data:data.areas;if(!Array.isArray(incoming))throw new Error();if(areas.length&&!confirm('A importação substituirá o banco de áreas deste navegador. Continuar?'))return;areas=incoming;saveAreas();alert(`${areas.length} áreas importadas com sucesso.`);}catch{alert('Este arquivo não é um backup válido do Banco de Áreas.');}finally{e.target.value='';}});
$('#backup-all').addEventListener('click',()=>{const payload={app:'Castel Brain',version:1,exportedAt:new Date().toISOString(),areas,reports:reportHistory},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`castel_brain_backup_completo_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);});
$('#restore-all').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.app!=='Castel Brain'||!Array.isArray(data.areas)||!Array.isArray(data.reports))throw new Error('formato inválido');if(!confirm(`Restaurar ${data.reports.length} relatórios e ${data.areas.length} áreas? Os dados atuais deste navegador serão substituídos.`))return;localStorage.setItem(AREA_STORAGE,JSON.stringify(data.areas));localStorage.setItem(REPORT_STORAGE,JSON.stringify(data.reports));areas=data.areas;reportHistory=data.reports;compareIds=[];renderAreas();renderHistory();alert('Backup completo restaurado com sucesso.');}catch(err){alert('Não foi possível restaurar este arquivo. Verifique se ele é um backup completo do Castel Brain e se há espaço disponível.');}finally{e.target.value='';}});
loadAreas();loadHistory();

